version: "2"
services:
  gulp-sass:
    build: .
    image: my/docker-gulp-sass
    container_name: 'gulp-sass'
    tty: true
    command: "gulp watch"
    volumes:
      - ./src/scss:/src/scss
      - ./src/css:/src/css
      - ./gulpfile.js:/src/gulpfile.js
      - ./package.json:/src/package.json

